import images from './images';
const dummyData = {
    myProfile: {
        profile_image: images.LOGO,
        name: "Loi Cao"
    },
    STATUS_ID : {
        0: 'DELETED',
        1: 'UNCOMPLETED',
        2: 'COMPLETED',
        3: 'BUG',
        4: 'EXPIRED'
    },
    STATUS_NAME :{
        'DELETED': 0,
        'UNCOMPLETED' : 1,
        'COMPLETED' : 2,
        'BUG': 3,
        'EXPIRED' : 4
    },
    JOB_BAR_STATUS : [
        {job:'completedJobs', task:'completedTask'},
        {job:'unCompletedJobs', task:'unCompletedTask'},
        {job:'expiredJobs', task:'expiredTask'},
        {job:'bugJobs', task:'bugTask'}
    ],
    STATUS : {
        COMPLETED: 'completed',
        UNCOMPLETED: 'unCompleted',
        EXPIRED: 'expired',
        BUG: 'bug'
    },
    CATEGORY_STATUS:[
        // {id:0, status:'Deleted'},
        {id:1, status: 'Uncompleted'},
        {id:2, status: 'Completed'},
        {id:3, status: 'Bug'},
        {id:4, status: 'Expired'}
    ],
    allTask: [
        {
            content: "New content",
            deadline: "02/02/2023 00:00:00",
            idGroup: 13,
            idProject: 10,
            idTask: 1,
            mailUserCreateGroup: "Hello@gmail.com",
            mailUserCreateProject: "Hello@gmail.com",
            nameGroup: "hello kitty",
            nameProject: "Hello kitty 1",
            nameTask: "New task",
            nameUserCreateGroup: "Hello",
            nameUserCreateProject: "Hello",
            phoneUserCreateGroup: "0394653441",
            phoneUserCreateProject: "0394653441",
            projectCreateDate: "02/08/2022 14:18:42",
            statusId: 2,
            statusName: "Hoàn thành",
            taskCreateDate: "02/08/2022 15:56:51",
            updateDate: "02/08/2022 16:10:08",
            userCreateGroup: 1,
            userCreateProject: 1,
        },
        {
            content: "Hello",
            deadline: "05/08/2009 14:40:52",
            idGroup: 13,
            idProject: 10,
            idTask: 2,
            mailUserCreateGroup: "Hello@gmail.com",
            mailUserCreateProject: "Hello@gmail.com",
            nameGroup: "hello kitty",
            nameProject: "Hello kitty 1",
            nameTask: "Hello project 10",
            nameUserCreateGroup: "Hello",
            nameUserCreateProject: "Hello",
            phoneUserCreateGroup: "0394653441",
            phoneUserCreateProject: "0394653441",
            projectCreateDate: "02/08/2022 14:18:42",
            statusId: 4,
            statusName: "Quá hạn",
            taskCreateDate: "02/10/2022 11:33:05",
            updateDate: "02/10/2022 11:33:05",
            userCreateGroup: 1,
            userCreateProject: 1,
        },
        {
            content: "some content",
            deadline: "05/27/2022 00:00:00",
            idGroup: 13,
            idProject: 14,
            idTask: 4,
            mailUserCreateGroup: "Hello@gmail.com",
            mailUserCreateProject: "Hello@gmail.com",
            nameGroup: "hello kitty",
            nameProject: "Hello Kitty",
            nameTask: "test api 2",
            nameUserCreateGroup: "Hello",
            nameUserCreateProject: "Hello",
            phoneUserCreateGroup: "0394653441",
            phoneUserCreateProject: "0394653441",
            projectCreateDate: "02/09/2022 20:51:14",
            statusId: 2,
            statusName: "Hoàn thành",
            taskCreateDate: "02/26/2022 19:51:00",
            updateDate: "02/26/2022 19:51:00",
            userCreateGroup: 1,
            userCreateProject: 1,
        },
        {
            content: "some content",
            deadline: "05/05/2022 00:00:00",
            idGroup: 13,
            idProject: 10,
            idTask: 5,
            mailUserCreateGroup: "Hello@gmail.com",
            mailUserCreateProject: "Hello@gmail.com",
            nameGroup: "hello kitty",
            nameProject: "Hello kitty 1",
            nameTask: "test api task 3",
            nameUserCreateGroup: "Hello",
            nameUserCreateProject: "Hello",
            phoneUserCreateGroup: "0394653441",
            phoneUserCreateProject: "0394653441",
            projectCreateDate: "02/08/2022 14:18:42",
            statusId: 1,
            statusName: "Chưa hoàn thành",
            taskCreateDate: "02/26/2022 20:04:44",
            updateDate: "02/26/2022 20:04:44",
            userCreateGroup: 1,
            userCreateProject: 1,
        },
        {
            content: "some content",
            deadline: "05/05/2022 00:00:00",
            idGroup: 13,
            idProject: 10,
            idTask: 6,
            mailUserCreateGroup: "Hello@gmail.com",
            mailUserCreateProject: "Hello@gmail.com",
            nameGroup: "hello kitty",
            nameProject: "Hello kitty 1",
            nameTask: "test api task 4",
            nameUserCreateGroup: "Hello",
            nameUserCreateProject: "Hello",
            phoneUserCreateGroup: "0394653441",
            phoneUserCreateProject: "0394653441",
            projectCreateDate: "02/08/2022 14:18:42",
            statusId: 1,
            statusName: "Chưa hoàn thành",
            taskCreateDate: "02/26/2022 20:04:52",
            updateDate: "02/26/2022 20:04:52",
            userCreateGroup: 1,
            userCreateProject: 1,
        },
        {
            content: "Old content",
            deadline: "02/02/2023 00:00:00",
            idGroup: 13,
            idProject: 10,
            idTask: 8,
            mailUserCreateGroup: "Hello@gmail.com",
            mailUserCreateProject: "Hello@gmail.com",
            nameGroup: "hello kitty",
            nameProject: "Hello kitty 1",
            nameTask: "New task",
            nameUserCreateGroup: "Hello",
            nameUserCreateProject: "Hello",
            phoneUserCreateGroup: "0394653441",
            phoneUserCreateProject: "0394653441",
            projectCreateDate: "02/08/2022 14:18:42",
            statusId: 3,
            statusName: "Hoàn thành",
            taskCreateDate: "02/08/2022 15:56:51",
            updateDate: "02/08/2022 16:10:08",
            userCreateGroup: 1,
            userCreateProject: 1,
        },
    ]
}

export default dummyData